lib/offsite_payments/helper.rb
lib/offsite_payments/integrations/a1agregator.rb
lib/offsite_payments/integrations/chronopay.rb
lib/offsite_payments/integrations/direc_pay.rb
lib/offsite_payments/integrations/dotpay.rb
lib/offsite_payments/integrations/e_payment_plans.rb
lib/offsite_payments/integrations/ipay88.rb
lib/offsite_payments/integrations/mollie_ideal.rb
lib/offsite_payments/integrations/nochex.rb
lib/offsite_payments/integrations/pag_seguro.rb
lib/offsite_payments/integrations/pay_fast.rb
lib/offsite_payments/integrations/payflow_link.rb
lib/offsite_payments/integrations/paypal.rb
lib/offsite_payments/integrations/pxpay.rb
lib/offsite_payments/integrations/valitor.rb
lib/offsite_payments/notification.rb
offsite_payments.gemspec
test/remote/remote_mollie_ideal_test.rb
test/unit/integrations/mollie_ideal/mollie_ideal_helper_test.rb
test/unit/integrations/pag_seguro/pag_seguro_helper_test.rb
test/unit/integrations/pxpay/pxpay_module_test.rb
test/unit/notification_test.rb

- Bumps ActiveUtils to 3.0 (currently in prerelease)
- Removes `json` gem dependency; it is included in the ruby standard library since 1.9.
- Update all `ActiveMerchant` code mentions to `ActiveUtils`
@karlhungus @ntalbott

Bump acive_utils to 3.0, update namespace

---

CHANGELOG.md
lib/offsite_payments/version.rb

@girasquid I don't think a major release is necessary, so I bumped it to 2.1.0.

Update CHANGELOG and bump version to 2.1.0

---

lib/offsite_payments/integrations/mollie.rb
lib/offsite_payments/integrations/mollie_ideal.rb
lib/offsite_payments/integrations/mollie_mistercash.rb
test/fixtures.yml
test/remote/remote_mollie_mistercash_test.rb
test/unit/integrations/mollie_ideal/mollie_ideal_module_test.rb
test/unit/integrations/mollie_mistercash/mollie_mistercash_helper_test.rb
test/unit/integrations/mollie_mistercash/mollie_mistercash_module_test.rb
test/unit/integrations/mollie_mistercash/mollie_mistercash_notification_test.rb

- Added Mollie Mistercash integration
- Refactored Mollie API/redirect creation to a parent module
- Fixed failing tests in `remote_mollie_ideal_test.rb`
- Added tests for `mollie_mistercash.rb`
For testing I tried both checkouts locally and they worked for me. I was not able to test the redirection back to Shopify.
@wvanbergen @girasquid

Added Mollie Mistercash 

---

lib/offsite_payments/integrations/yuupay.rb
test/unit/integrations/yuupay/yuupay_module_test.rb

Fixes: The integration currently breaks Shopify because `Yuupay.return` doesn't exist. 
@girasquid @j-mutter review please

Adding class methods to yuupay integration

---

lib/offsite_payments/integrations/coinbase.rb
test/unit/integrations/coinbase/coinbase_notification_test.rb

Coinbase sends a total_original parameter if a gateway discount is set.  If this parameter is present, it should be used for calculating the order's total.

Add support for total_original Coinbase parameter

---

lib/offsite_payments/integrations/directebanking.rb
test/unit/integrations/directebanking/directebanking_helper_test.rb

SofortBanking (formerly directebanking) has asked us to stop submitting the description field (`shop.name` - `checkout.id`) as the `reason_1` field, as it's getting truncated, and is no longer unique. Instead we'll begin sending the `checkout.id` as the `reason_1` field, via `:order`.
Please review @odorcicd

update reason1 field per sofort request

---

lib/offsite_payments/integrations/gestpay.rb
test/unit/integrations/gestpay/gestpay_notification_test.rb

Currently, the Notification for Gestpay will [raise a GestpayEncryptionResponseError if the server tells us there was an error](https://github.com/Shopify/offsite_payments/blob/master/lib/offsite_payments/integrations/gestpay.rb#L40-L41). 
This is handled [in the helper](https://github.com/Shopify/offsite_payments/blob/master/lib/offsite_payments/integrations/gestpay.rb#L107-L112), but not in the notification, so we end up throwing exceptions instead of marking the transaction as failed. I just set the [`status` as anything other than successful](https://github.com/Shopify/offsite_payments/blob/master/lib/offsite_payments/integrations/gestpay.rb#L154-L161), which is then detected as a failure, instead of blowing up.
@aprofeit @wvanbergen

Gestpay error handling

---

lib/offsite_payments/integrations/direc_pay.rb
test/unit/integrations/direc_pay/direc_pay_return_test.rb

Failed payments are currently considered as pending. Based on latest documentation (link?), it should now be safe not to do this.
@j-mutter @volmer @andrewpaliga @silverstreaked

DirecPay stops treating failed payments as pending

---

lib/offsite_payments/helper.rb
lib/offsite_payments/integrations/klarna.rb
test/unit/integrations/klarna/klarna_helper_test.rb

Exactly what the title says, plus updates the Klarna endpoint.
@christianblais @girasquid

Allow checkout tokens to be passed into forms

---

lib/offsite_payments/integrations/realex.rb
test/unit/integrations/realex/realex_module_test.rb

Shopify passes in `order` as an integer. 
@girasquid @ivanfer

fix bug - order is not string

---

lib/offsite_payments/integrations/universal.rb
test/unit/integrations/universal/universal_helper_test.rb

@andrewpaliga @girasquid for review.
This should be reverted once the Universal Offsite Dev Kit is not needed anymore.

Do not send credential3 with when it is the forward URL

---

lib/offsite_payments/integrations/coinbase.rb
test/unit/integrations/coinbase/coinbase_notification_test.rb

Added error handling on invalid or empty JSON payload for the Coinbase Notification Integration.
Tested `params` and `acknowledge`, as both will use `parse` (`params` will be parsed through the constructor though).
Please review @andrewpaliga @masaruhoshi

Rescue on JSON Parse error

---

lib/offsite_payments/integrations/sage_pay_form.rb
test/unit/integrations/sage_pay_form/sage_pay_form_helper_test.rb

@girasquid @aprofeit  for review
Also verifying changes with Sage Pay.

Make VendorTxCode unique

---

lib/offsite_payments/integrations/sage_pay_form.rb
test/unit/integrations/sage_pay_form/sage_pay_form_helper_test.rb

Reverts activemerchant/offsite_payments#165
This revers the change makes the order number for sage pay out of range
>RangeError: 371608070920150904173138 is out of range for ActiveRecord::Type::Integer with limit 8
I propose we revert this and push them onto the [Hosted Payment SDK](https://docs.shopify.com/hosted-payment-sdk). I want to limit the amount of custom solutions we introduce to circumvent their incorrect handling of our checkout ids.
@girasquid @aprofeit

Revert "Make VendorTxCode unique"

---

CHANGELOG.md
lib/offsite_payments/version.rb
offsite_payments.gemspec

We have moved some logic from Shopify to ActiveUtils [here](https://github.com/Shopify/active_utils/pull/64) and now in order to remove it from Shopify we need to bump this gem's dependency as well.

Bump active_utils dependency

---

.travis.yml
Gemfile.rails5
lib/offsite_payments.rb
offsite_payments.gemspec
test/unit/action_view_helper_test.rb

The only required changes were to remove an unused require that was removed in Rails 5 and to change the gemspec to allow this gem to be installed with that version.

Allow to use this gem with Rails 5

---

.travis.yml

Ruby 1.9 is no longer supported as of [Feb 23](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) and our [CI builds are breaking](https://travis-ci.org/activemerchant/offsite_payments/builds/122329844) because some gems we use no longer support ruby 1.9. Let's not test for an unsupported ruby version any more.
@girasquid @ThereExistsX

Stop testing ruby 1.9

---

lib/offsite_payments/return.rb
test/unit/return_test.rb

Currently this will blow up if there is ever a query string with a nil key/value.
```
query_string.split('&').inject({}) do |memo, chunk|
next **memo** if chunk.empty?
key, value = chunk.split('=', 2)
next **memo** if key.empty?
value = value.nil? ? nil : CGI.unescape(value)
memo[CGI.unescape(key)] = value
memo
end
```
The bold fixes it.

Inject loop not returning hash on guard clauses.

---

lib/offsite_payments/integrations/universal.rb
test/unit/integrations/universal/universal_notification_test.rb
test/unit/integrations/universal/universal_return_test.rb

This makes it so that `Universal` gateways can include `x_message` in payload to Shopify. We need this for [COD app](https://github.com/Shopify/cod-app) so that it to return a custom failure message upon payment failure. @aprofeit let me know if this makes sense or if there's a better way to do this somewhere. cc @quelledanielle @kyledurand

Add x_message to Universal gateway

---

lib/offsite_payments/integrations/mollie_ideal.rb

Friesland Bank has been taken over by Rabobank and was shut down in 2013: https://www.rabobank.nl/particulieren/frieslandbank/
Bunq is a new bank that acquired its license in 2015: https://www.nrc.nl/nieuws/2015/11/25/bunq-whatsapp-voor-banken-1559753-a310271

Update Dutch banks for Mollie iDEAL 🇳🇱

---

lib/offsite_payments/integrations/payu_in.rb
test/unit/integrations/payu_in/payu_in_helper_test.rb

**What are you trying to accomplish with this PR?**
Right now, phone field is sent as a basic string to PayU and includes spaces and other characters. The problem is that PayU doesn't allow users to pay if the phone numbers is not digits only.
See this screenshot where the phone is filled but PayU doesn't show any error, it just grays out the pay button.
When removing the space, everything works as expected.
**How is this accomplished?**
Add a specific regex to sanatize phone fields.
@pi3r @jasonwebster

Send digits only phone to PayU

---

offsite_payments.gemspec

minimal version conflicts with https://github.com/Shopify/money

removes minimum money dependency

---

lib/offsite_payments/integrations/payu_in.rb

Using `gsub!` on fields that could be frozen is dangerous.

Swap gsub! for gsub for safety.

---

.travis.yml
lib/offsite_payments.rb
lib/offsite_payments/integrations/realex_offsite.rb
test/unit/integrations/realex_offsite/realex_offsite_helper_test.rb

**Why**
```ruby
(9.29.to_f * 100).to_i == 928
```
**What**
Use decimals instead of floats. Also added a regression test
**More info**
http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

realex_offsite to_f rounding error

---

offsite_payments.gemspec

Bumping active_utils dependency to `~> 3.3.0`, to support changes implemented on https://github.com/Shopify/active_utils/pull/78 and https://github.com/Shopify/active_utils/pull/79.
Here is the https://github.com/Shopify/active_utils/compare/v3.2.5...v3.3.0
Some changes on Shopify changed Kosovo's ISO code from `KV` to `XK`, so we have to bump all related gems.
Reference links:
https://countrycode.org/kosovo
https://en.wikipedia.org/wiki/Kosovo
Closing https://github.com/activemerchant/offsite_payments/pull/230 in favor of this one.
⚠️  Right now we don't have a branch where we can merge this into.

Bump active_utils to 3.3.0

---

offsite_payments.gemspec

https://github.com/Shopify/active_utils/compare/v3.2.0...v3.3.0

bump active_utils version 3.3.0

---

lib/offsite_payments/integrations/realex_offsite.rb

This simply adds a guard against nils being passed into the digit extraction method. 
Address data is not guaranteed to be part of incoming parameters, which causes `extract_digits` to throw exceptions.

[Realex] guard against nil when extracting AVS code

---

lib/offsite_payments/integrations/universal.rb
test/unit/integrations/universal/universal_helper_test.rb

**What are you trying to accomplish with this PR?**
only use fields that start with `x_` to generate the signature so we can use `add_field` without worrying about changing the signature unintentionally.

only use fields that start with `x_` to generate the signature

---

lib/offsite_payments/integrations/citrus.rb

Compare using money object instead of decimals.

[Citrus] compare Money object in Notification#amount_ok?

---

lib/offsite_payments/integrations/mollie.rb

This curly bracket causes issues when calling the Mollie API with extra parameters.

	Remove stray curly bracket

---

lib/offsite_payments/integrations/bit_pay.rb
test/unit/integrations/bit_pay/bit_pay_helper_test.rb
test/unit/integrations/bit_pay/bit_pay_notification_test.rb

Silently swallowing errors is an anti-pattern, we're unable to see if something's wrong and retry in that case.

Remove `rescue JSON::ParseError nil` pattern in BitPay integration

---

lib/offsite_payments/integrations/sage_pay_form.rb
test/unit/integrations/sage_pay_form/sage_pay_form_helper_test.rb

Do not include `locale` field for SagePay

Do not include `locale` field for SagePay

---

lib/offsite_payments/integrations/moneybookers.rb
test/unit/integrations/moneybookers/moneybookers_module_test.rb

https://www.moneybookers.com/app/payment.pl is a legacy URL which will be discontinued on September 1th 2017.
The most recent documentation can be found on https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf

update Skrill API URL

---

offsite_payments.gemspec

Per @rafaelfranca's (a member of the Rails core team) comment[1]:
>I'd not do this. 5.2 may contains breaking changes, usually for gems of this size it works, but the Rails team doesn't recommend to use the same rules as the semver since we use shifted semver.
1: https://github.com/activemerchant/offsite_payments/commit/cc772fdf6115ce2a4bbc73c99b58a70f60908a28#commitcomment-22021971

Constrain dependency according to Rails' shifted semver

---

lib/offsite_payments/integrations/paytm.rb

With `reduce`, we need to return the `memo` from the block. In this case, we weren't, hence the resulting value of the assignation was used as the `memo` value forwarded to the next loop, generating exceptions.
A simple solution would have been to use `slice` on `@fields`, but we still need keys that could potentially be in `CHECKSUM_FIELDS` and not in `fields` to generate the proper signature.

Fix PayTM checksum generation

---

lib/offsite_payments/integrations/payu_in.rb
test/unit/integrations/citrus/citrus_return_test.rb
test/unit/integrations/molpay/molpay_return_test.rb

The `PayuIn#amount_ok?` method initializes a BigDecimal with the discount as given in the params.
If the discount value is invalid as an argument for BigDecimal (e.g. '0.'), then the latest BigDecimal v1.3.2 (bundled by default in Ruby 2.4) raises an exception.
The behaviour of the current version of BigDecimal is to silently initialize any invalid arguments to a value of 0.00.
To support the new BigDecimal and preserve current behaviour, the method now uses `discount.to_d` to create a BigDecimal for purposes of zero coercion, instead of `BigDecimal.new(discount.to_s)`.

Fix discount BigDecimal initialization in PayuIn#amount_ok?

---

lib/offsite_payments/integrations/payu_in.rb

`nil#to_d` doesn't exist, so we need to handle the case where the discount param is `nil`.

Account for nil discount in Payu gateway

---

lib/offsite_payments/integrations/world_pay.rb
test/unit/integrations/world_pay/world_pay_helper_test.rb

The current mapping for WorldPay concatenates `address1`, `address2`, `city` & `state` into one field "address".
That caused address to be displayed weirdly on WorldPay's end.
WorldPay does support sending address fields separately. [WorldPay Specification](http://support.worldpay.com/support/kb/bg/htmlredirect/htmlredirect.htm?_ga=2.98809374.1679648923.1513589946-2013789715.1513589946#rhtml/HTML_Redirect_parameters.htm%3FTocPath%3D_____8)
This PR removes the need to concatenate address data.

[WorldPay] Use multiple address fields

---

Gemfile.lock

The Gemfile.lock wasn't reflecting changes to the Gemfile in the previous PR [#276](https://github.com/activemerchant/offsite_payments/pull/276)

Updated Gemfile.lock to reflect latest changes

---

lib/offsite_payments/integrations/paytm.rb

The current implementation assumes an email should always be used for customer identifier. That isn't always the case, as we often only receive a phone number. This change makes sure we fallback to the phone number when email isn't provided.
We also need to sanitize identifiers prior to sending them to PayTM, the same way we sanitize them before generating the checksum. Characters such as `+` (present in phone numbers) won't pass the validation on their side and will fail the transaction.

Paytm to accepts phone numbers as customer identifier

---

lib/offsite_payments/integrations/mollie.rb
test/unit/integrations/mollie/mollie_test.rb

Wrapped the get_request of Mollie integration with `retry_exceptions` so that it retry on timeout. This should prevent abandoned checkout when a random timeout happen.

Add GET retries for Mollie offsites

---

lib/offsite_payments/integrations/paytm.rb

In `customer`, we do;
```
customer_id =
if options[:email].present?
sanitize_field(options[:email])
else
sanitize_field(options[:phone])
end
```
It calls `sanitize_field`, which in its current form, calls `gsub!`. Since `gsub!` modifies the content in place, it doesn't return any value, hence `customer_id` is always `nil`.
```
irb(main):006:0> "abc".gsub!(/^a-z/, '')
=> nil
irb(main):007:0> "abc".gsub(/^a-z/, '')
=> "abc"
```
This patch modifies the behaviour of `sanitize_field` to return the new sanitized value.
🎩 'ed with both flows, phone and email.

Ensure values are always sanitized

---

lib/offsite_payments/integrations/bit_pay.rb

Removes `rescue` from `BitPay#create_invoice`. When an error occurs it should bubble up instead of being swallowed.

[BitPay] Removes rescue during invoice creation

---

CHANGELOG.md
Gemfile.lock
lib/offsite_payments/version.rb

Bump version to 2.6.8, it includes:
- Ensure values are always sanitized [christianblais] #281
- Updates exception handling for BitPay [joshnuss] #282

Bumps version to 2.6.8

---

.travis.yml
Gemfile
Gemfile.lock
README.md
gemfiles/Gemfile.rails32
gemfiles/Gemfile.rails40
gemfiles/Gemfile.rails41
gemfiles/Gemfile.rails42
gemfiles/Gemfile.rails50
gemfiles/Gemfile.rails51
gemfiles/Gemfile.rails52
gemfiles/Gemfile.shopify
lib/offsite_payments.rb
offsite_payments.gemspec

Since Shopify is releasing the shopify-money gem to public, this won't
be included by default, but still required.
Post install message
```
🏈 in testing at (master) $ gem install /Users/filipecosta/src/github.com/filipebarcos/offsite_payments/offsite_payments-2.6.8.gem
In order to use `offsite_payments` gem, you need to either install or add to your Gemfile
one of the two options for Money gem:
- `gem 'money'`
- `gem 'shopify-money', require: 'money'`
Regardless of which gem you choose, please add them *before* `offsite_payments`.
For more info, go to https://github.com/filipebarcos/offsite_payments#money-gem-dependency
Successfully installed offsite_payments-2.6.8
1 gem installed
```
`fail` looks like this:
```
🏈 in testing at (master) $ irb
>> require 'offsite_payments'
Traceback (most …
```

Remove Money gem as dependency into gemspec

---

lib/offsite_payments/integrations/mollie_ideal.rb

Hi, we have recently added Moneyou as iDEAL issuer.
I've added Moneyou in this PR.

Complete the list of Mollie iDEAL issuers

---

lib/offsite_payments/integrations/mollie_ideal.rb
test/remote/remote_mollie_ideal_test.rb
test/unit/integrations/mollie_ideal/mollie_ideal_module_test.rb

> We have removed the test issuers. For iDEAL, the issuers should be identical between live and test mode. So, what you'd previously send for live mode, can now be sent for all modes. This is reflected in our issuers API but I'm not sure you guys are using that. -- Mollie
closes https://github.com/activemerchant/offsite_payments/issues/293
closes https://github.com/Shopify/shopify/issues/155669
Removed test issuers, in favour of a test mode with a live issuer. Remote test api key in fixtures is no longer valid, I've tested with my own key and tests pass.

remove test issuers

---

lib/offsite_payments/integrations/mollie.rb
lib/offsite_payments/integrations/mollie_ideal.rb
lib/offsite_payments/integrations/mollie_mistercash.rb
test/unit/integrations/mollie_ideal/mollie_ideal_helper_test.rb
test/unit/integrations/mollie_mistercash/mollie_mistercash_helper_test.rb

The code was expecting that the URLs always contained query strings, but that is no longer the case. This PR removes the dependency on query string parameters.
TODO:
Here are some examples of URLs we get from iDEAL:
- https://pay.mollie.nl/payment/start/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- https://www.abnamro.nl/nl/ideal/identification.do?randomizedstring=xxxxxxxxxx&trxid=xxxxxxxxxxxxxx
- https://diensten.regiobank.nl/online/ideal/#/sign?sp=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&trxid=xxxxxxxxxxxxxxxx 
- https://bcr.girogate.be/bi/t2bc?tx=xxxxxxxxx&rs=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&cs=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- https://www.mollie.com/payscreen/out/xxxxxxxxxx
- https://www.mollie.com/paymentscreen/testmode/?method=ideal&token=xxxxxx
- …

[Mollie iDEAL] Remove requirement for query string parameters

---

lib/offsite_payments/integrations/moneybookers.rb
test/unit/integrations/moneybookers/moneybookers_notification_test.rb

When a payment fails Skrill will post the failed reason code to the merchant/shopping cart status_url. The mapped failure reason should be displayed in the orders section of the Shopify
backend.
The most recent documentation can be found on https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf

Add failure reasons for Moneybookers (Skrill) integration

---

lib/offsite_payments/integrations/payu_in.rb
test/unit/integrations/payu_in/payu_in_return_test.rb

Map "pending" status returned by Payu_In PG to 'Failed'
979 tests, 2689 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

map payu_in pg status pending as Failed

---

lib/offsite_payments/integrations/paytm.rb
test/unit/integrations/paytm/paytm_notification_test.rb

Paytm notifications were no longer working since they added a new parameter
`TXNDATETIME` to their notification and checksum generation on their backend.
With this commit we aim to fix the checksum verification so it macthes how it
is done in Paytm's backend.

Add `TXNDATETIME` to the whitelist of params to use for checksum verification

---

.travis.yml
gemfiles/Gemfile.latest-release
gemfiles/Gemfile.rails-edge
offsite_payments.gemspec

Live on the Rails edge. We can test the gem against latest Rails release (5.2) and Rails HEAD. Currently we have an upperbound constraint on ActionPack. We can remove this to be less conservative and not require it to be manually updated with future Rails releases. Since we will be testing against latest Rails automatically this should be safe as well.
resolves https://github.com/activemerchant/offsite_payments/issues/312

Live and Test against Rails edge

---

lib/offsite_payments/integrations/bit_pay.rb
test/unit/integrations/bit_pay/bit_pay_helper_test.rb

The V2 API needs the token upon invoice creation, as per BitPay people
it's also fine to pass it to V1

[Bitpay] Add token to payload while creating the invoice

---

lib/offsite_payments/integrations/bit_pay.rb
test/unit/integrations/bit_pay/bit_pay_helper_test.rb

BitPay gateway implements API v2 authentication for newer implementations

[Bitpay] Add token check for API v2 endpoints

---

lib/offsite_payments/integrations/bit_pay.rb
test/unit/integrations/bit_pay/bit_pay_helper_test.rb

The v1 logic was fetching the invoice id using `invoice['id']` and this was used also by v2.
This change makes v2 use `invoice['data']['id']`

[BitPay] properly fetch the invoice id after creation

---

lib/offsite_payments/integrations/bit_pay.rb
test/unit/integrations/bit_pay/bit_pay_notification_test.rb

The previous version of the  BitPay integration was returning the payload directly in the root
of the json payload. This now needs to be accessed through the `data` key. See https://bitpay.com/invoices/VAGTTqCZJFSiQpuXW2pFTD for an example.

[BitPay] Read information from the `data` key present in the payload instead of root

---

lib/offsite_payments/integrations/bit_pay.rb
test/unit/integrations/bit_pay/bit_pay_notification_test.rb

Previous changes to BitPay https://github.com/activemerchant/offsite_payments/pull/328 introduced a bug since the payload from an API and the payload present on the api aren't similar. This will set the params of the notification to `JSON.parse(body)['data']` if there is a `data` key or will set it to `JSON.parse(body) otherwise.

[Bitpay] Fixes an issue where notification couldn't be acknowledged

---

lib/offsite_payments/integrations/bit_pay.rb
test/unit/integrations/bit_pay/bit_pay_notification_test.rb

Previous of the code was comparing the whole payload between the IPN and the API request. This is causing issues because payload have evovled quite a lot since this integration was written. This only compares transaction_id/status which are certified to be present in both payload.

[BitPay] Only compare transaction_id/status while acknowledging

---

lib/offsite_payments/integrations/realex_offsite.rb
test/unit/integrations/realex_offsite/realex_offsite_helper_test.rb

`Shopify` is hardcoded as a parameter sent to Realex. There is already a pattern for this, which is to use the application_id accessor.

[Realex] Use application_id instead of hardcoded Shopify

---

lib/offsite_payments.rb
lib/offsite_payments/integrations/universal.rb

Related to https://github.com/Shopify/shopify/issues/232781
It's generally agreed upon that HUF should have two minor subunits
(ex. https://stripe.com/docs/currencies), instead of the zero subunits
as defined in this gem. This can cause rounding issues when sending to the
gateway. 
By default all currencies have two minor subunits, unless otherwise specified.
https://github.com/activemerchant/offsite_payments/blob/cd56e7897fe91f8dbbfb8185e95449f16e07c921/lib/offsite_payments/integrations/universal.rb#L129-L132
cc @elfassy @pi3r

Remove special subunit case for HUF in universal integration

---

lib/offsite_payments/integrations/paxum.rb

In Rails edge, deprecate `starts_with?` and `ends_with?` for String core extensions.
Ref https://github.com/rails/rails/pull/39152.
So it seems pull requests are failed since this summer. (#344 and later issues)
Prior to this pull request, I confirmed this commit on my forked repository.
https://github.com/akiko-pusu/offsite_payments/pull/2

FIX build failed / Change to use `String#start_with?` instead of `String#starts_with?`.

---

gemfiles/Gemfile.shopify

The `Gemfile.shopify` file doesn't specify a version of money to use. I'm not entirely sure _why_ that's the case, but it seems like an unnecessary risk to me that can just lead to headaches.
A particular headache I'm currently experiencing (and that's prompting me to lock this) is that Money 0.15 was just released (https://github.com/Shopify/money) and [several tests began to fail](https://github.com/activemerchant/offsite_payments/runs/1736831871) because of that.
Let's keep the minor version locked for now to prevent breakages introduced by functionality changes.
We can bump the money gem to 0.15 in a follow up PR, for now we need to create a release for a fix for Gestpay https://github.com/activemerchant/offsite_payments/pull/352

Lock Gemfile-shopify to money 0.14.x

---

.github/workflows/ruby-ci.yml

This is a followup to the same PR in [activemerchant/payment_icons](https://github.com/activemerchant/payment_icons/pull/400), so we Github Actions behavior similar in other `activemerchant` repos.

Run GitHub Actions CI on PRs

---

.github/workflows/ruby-ci.yml

Since Rails Edge only supports Ruby 2.7 according to the [edge documentation](https://edgeguides.rubyonrails.org/getting_started.html#installing-ruby), we're disabling `Gemfile.rails-edge` for Ruby 2.5 and 2.6.

Disable Rails Edge for Ruby 2.5 and 2.6

---

.github/workflows/ruby-ci.yml
gemfiles/Gemfile.shopify
lib/offsite_payments/helper.rb
lib/offsite_payments/integrations/direc_pay.rb
lib/offsite_payments/integrations/directebanking.rb
lib/offsite_payments/integrations/hi_trust.rb
lib/offsite_payments/integrations/ipay88.rb
lib/offsite_payments/integrations/nochex.rb
test/unit/integrations/direc_pay/direc_pay_helper_test.rb
test/unit/integrations/directebanking/directebanking_helper_test.rb
test/unit/integrations/hi_trust/hi_trust_helper_test.rb
test/unit/integrations/nochex/nochex_helper_test.rb

For solving [issue](https://shopify-money.atlassian.net/browse/PPI-18?atlOrigin=eyJpIjoiYThjNzAwN2M0MzNmNGY2MDg1NjZjNTZhOGFhMzBkZDEiLCJwIjoiaiJ9). Bump the version of gem `shopify-money` and make the integrations compatible for both `shopify-money` and `money` gem.
The reason why this change is needed. https://github.com/Shopify/money/pull/221 this makes [shopify-money](https://github.com/Shopify/money/pull/221) gem and [money](https://github.com/RubyMoney/money) gem incompatible, and some integrations are still rely on the money object.

Bump money gem

---

Gemfile.lock
offsite_payments.gemspec

Same as https://github.com/activemerchant/offsite_payments/pull/383

Remove upper bound on active utils

---

Gemfile.lock
README.md
offsite_payments.gemspec

Shopify wants to update offsite_payments to 3.0. However, there is a conflicting dependency on `shopify-money`. In core, we want 3.0 but offsite_payments specifies `~> 2.0`.
This dependency is only present in the gemspec, but not in Gemfile - it's unbounded there.
Additionally, since version 3.0 this gem [no longer supports non-Shopify Money gem](https://github.com/activemerchant/offsite_payments/pull/386/files#), so removed that section from the README.

Change shopify-money version to >= 2.0 in gemspec.
