activemerchant/offsite_payments

lib/offsite_payments/integrations/realex.rb
test/unit/integrations/realex/realex_helper_test.rb
test/unit/integrations/realex/realex_notification_test.rb

@j-mutter @girasquid @davidjrice can you review please?

use credentials 1,2,3 vs. 2,3,4

---

offsite_payments.gemspec

@girasquid Prepping for a release.

Bump active_utils to final 3.0 version

---

generators/templates/integration.rb
rails/init.rb

Clean up relative requires, and remove rails/init.rb

---

offsite_payments.gemspec
test/test_helper.rb
test/unit/integrations/ipay88/ipay88_module_test.rb

@girasquid use latest versions available, and fix a warning while we're at it.

Bump test dependencies, fix test warning

---

CONTRIBUTING.md
README.md
RELEASING

Update README, add CONTRIBUTING

---

lib/offsite_payments/integrations/universal.rb
lib/offsite_payments/integrations/yuupay.rb
test/unit/integrations/yuupay/yuupay_helper_test.rb

- Add yuupay (universal) gateway in separate file inheriting universal 
- Add unit tests for yuupay helper (only class that changes)
@bizla @j-mutter

Adding Yuupay gateway as universal

---

lib/offsite_payments/integrations/mollie.rb
lib/offsite_payments/integrations/mollie_mistercash.rb
test/remote/remote_mollie_ideal_test.rb
test/remote/remote_mollie_mistercash_test.rb
test/unit/integrations/mollie/mollie_test.rb

- Fixed broken mollie gateways (remote tests now pass and the checkout works)
- Added unit tests for uncovered methods `get_request` and `post_request`
@girasquid @bizla can you review please?

Adding fixes and tests

---

lib/offsite_payments/integrations/directebanking.rb
test/unit/integrations/directebanking/directebanking_helper_test.rb

Reverts Shopify/offsite_payments#81
Reverting until we can figure out what's up with this

Revert "update reason1 field per sofort request"

---

README.md

@louiskearns @mhashemi86 @girasquid

Updating readme with "no guarantee" blurb

---

lib/offsite_payments/integrations/world_pay.rb
test/unit/integrations/world_pay/world_pay_notification_test.rb

Adding IP range verification to Worldpay Offsite
@girasquid @j-mutter 
@louiskearns

Worldpay IP verification

---

lib/offsite_payments/integrations/citrus.rb
test/unit/integrations/citrus/citrus_return_test.rb

Pass `cancel_return_url` to citrus
@girasquid @ivanfer

Fixes thank you page on cancel

---

lib/offsite_payments/integrations/universal.rb
test/unit/integrations/universal/universal_helper_test.rb

@andrewpaliga can you review this?

Adding support for credentials 3 and 4

---

lib/offsite_payments/integrations/molpay.rb
test/unit/integrations/molpay/molpay_helper_test.rb
test/unit/integrations/molpay/molpay_notification_test.rb
test/unit/integrations/molpay/molpay_return_test.rb

Hi @andrewpaliga ,
I think this bugs has to do with the errors on the shopify offsite_gateway_callback

Bug fixed on mismatched skey & remove restriction on min amount

---

.travis.yml

@aprofeit @girasquid for review
http://docs.travis-ci.com/user/notifications/#Email-notifications
Most of us probably don't need to receive theses.

Only send travis emails to the person who signed the commit

---

lib/offsite_payments/integrations/klarna.rb

This updates Klarna's service url to support a production environment.
@girasquid  @andrewpaliga

update klarna service url

---

lib/offsite_payments/helper.rb
lib/offsite_payments/integrations/hi_trust.rb
test/unit/integrations/hi_trust/hi_trust_helper_test.rb

@AlenV Can you confirm that this is the behaviour desired for all merchants moving forward?
@girasquid @ivanfer

Switching depositflag to 0

---

lib/offsite_payments/helper.rb
lib/offsite_payments/integrations/hi_trust.rb
test/unit/integrations/hi_trust/hi_trust_helper_test.rb

Reverts activemerchant/offsite_payments#157
@girasquid @ivanfer

Revert "Switching depositflag to 0"

---

lib/offsite_payments/integrations/molpay.rb
test/unit/integrations/molpay/molpay_helper_test.rb

added notify_url and update unit test.

Update molpay.rb & helper_test.rb

---

Gemfile
Gemfile.rails32
Gemfile.rails40
Gemfile.rails41
Gemfile.rails42
Gemfile.rails5
lib/offsite_payments/integrations/citrus.rb
lib/offsite_payments/integrations/easy_pay.rb
lib/offsite_payments/integrations/liqpay.rb
lib/offsite_payments/integrations/pay_fast.rb
lib/offsite_payments/integrations/platron.rb
lib/offsite_payments/integrations/robokassa.rb
lib/offsite_payments/integrations/web_pay.rb
lib/offsite_payments/integrations/webmoney.rb
offsite_payments.gemspec
test/unit/integrations/citrus/citrus_notification_test.rb
test/unit/integrations/citrus/citrus_return_test.rb
test/unit/integrations/easy_pay/easy_pay_notification_test.rb
test/unit/integrations/pay_fast/pay_fast_notification_test.rb
test/unit/integrations/platron/platron_notification_test.rb
test/unit/integrations/robokassa/robokassa_notification_test.rb
test/unit/integrations/web_pay/web_pay_notification_test.rb
test/unit/integrations/webmoney/webmoney_notification_test.rb

Also test against Rails 5 release versions instead of master

Fix CI by not overriding the version requirement for the money gem

---

lib/offsite_payments/integrations/paytm.rb
test/unit/integrations/paytm/paytm_helper_test.rb
test/unit/integrations/paytm/paytm_module_test.rb
test/unit/integrations/paytm/paytm_notification_test.rb
test/unit/integrations/paytm/paytm_return_test.rb

Paytm Wallet

---

lib/offsite_payments/integrations/payu_in.rb
test/unit/integrations/payu_in/payu_in_helper_test.rb
test/unit/integrations/payu_in_paisa/payu_in_paisa_helper_test.rb

corrected zip parameter to from zip to zipcode

Changes to Offsite_payments PayU India

---

offsite_payments.gemspec
test/unit/integrations/mollie/mollie_test.rb

Use version of i18n >= 0.6.6 to fix security vulnerability https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4492

Use version of i18n >= 0.6.6

---

CHANGELOG.md
lib/offsite_payments/version.rb

Bumping Offsite_payments to reflect latest changes

Release 2.6.5

---

Gemfile.lock

Related to https://github.com/flavorjones/loofah/issues/144
`bundle update loofah`

Bumps loofah dependecy due to vulnerability

---

CHANGELOG.md
Gemfile.lock
lib/offsite_payments/version.rb

Bumps to 2.7.2

---

lib/offsite_payments/integrations/ipay88.rb
test/unit/integrations/ipay88/ipay88_module_test.rb

Update ipay88 due to deprecation

---

CHANGELOG.md
Gemfile.lock
lib/offsite_payments/version.rb

New version contains fixes for Mollie iDEAL + MisterCash #299

Bumps version to 2.7.4

---

lib/offsite_payments/integrations/paytm.rb
test/unit/integrations/paytm/paytm_helper_test.rb
test/unit/integrations/paytm/paytm_module_test.rb

PG Plus URL added

---

Gemfile.lock

The new version contain security fixes

Update sprockets to version 3.7.2

---

lib/offsite_payments/helper.rb

Document integration helper methods.

---

lib/offsite_payments/integrations/paytm.rb
test/unit/integrations/paytm/paytm_helper_test.rb
test/unit/integrations/paytm/paytm_module_test.rb

New URL for process transaction.

Update URL for Paytm

---

lib/offsite_payments/integrations/bit_pay.rb
test/unit/integrations/bit_pay/bit_pay_helper_test.rb

Update to see which version of the API merchants are using

api version tracking
